### ISSUE TITLE
Invalid "border" shorthanding

### ISSUE THREAD

**Issue by vmarkovtsev** [frankmarineau/shrthnd.js#2]
Current version produces invalid results for "border" property.

``` css
div {
  border-color: #ccc;
}
```

gets converted into

``` css
div {
  border: #ccc;
}
```

which is not right: border disappears at all in at least Chrome (requires "1px solid" prepended or similar). This bug prevents from using Bootstrap since there a lot of places where border-color is used there, e.g. `.btn-default`.
